### ISSUE TITLE
you should end yourself. 

### ISSUE THREAD

**Issue by Feel65** [wcaleniekubaa/TeaClient#5]
NOW. Give someone else a piece of that oxygen pie you’ve been hogging. You serve 0 purpose.

**Comment by wcaleniekubaa** [comment]
What the fuck is wrong with you guys?

**Comment by Feel65** [comment]
Why steal a brand?

**Comment by wcaleniekubaa** [comment]
I changed name.

**Comment by Zetvue** [comment]
> NOW. Give someone else a piece of that oxygen pie you’ve been hogging. You serve 0 purpose.

ok wtf is wrong with you

**Comment by Zetvue** [comment]
I made an issue cuz i thought it was a rat repo but holy shit I'm so sorry wcale

**Comment by wcaleniekubaa** [comment]
That's okay

**Comment by Feel65** [comment]
he’s a bit among us sussy
