### ISSUE TITLE
Quick Apologization

### ISSUE THREAD

**Issue by UnderscoreRayless** [wcaleniekubaa/TeaClient#6]
Hey, I apologize for the people who were being rude on your repo, none of those people represent us except KTibow, sorry for the inconvenience.

**Comment by Zetvue** [comment]
I apologize aswell. I thought it was a rat repo.

**Comment by wcaleniekubaa** [comment]
That's okay.

**Comment by wcaleniekubaa** [comment]
Also I have one questions, from where you got my repo?

**Comment by Zetvue** [comment]
> Also I have one questions, from where you got my repo?

I don't know tbh. One of our members posted a link to the repo.

![image](https://user-images.githubusercontent.com/87939327/170844143-278db05c-74e0-4842-b690-b16db445330d.png)
